%%
GREEN44DIS=simulateHouse(4,5,4,3,3,'distance');
GREEN44RICH=simulateHouse(4,5,4,3,3,'richer');
GREEN44YEAR=simulateHouse(4,5,4,3,3,'classyear');
bruteforcemincut(GREEN44YEAR)
bruteforcemincut(GREEN44RICH)
bruteforcemincut(GREEN44DIS)
%%
EMERSONYEAR=simulateHouse(15,12,32,31,3,'classyear');
EMERSONRICH=simulateHouse(15,12,32,31,3,'richer');
EMERSONDIS=simulateHouse(15,12,32,31,3,'distance');
bruteforcemincut(EMERSONYEAR)
bruteforcemincut(EMERSONRICH)
bruteforcemincut(EMERSONDIS)
%%
DUCKETTDIS=simulateHouse(9,5,11,15,3,'distance');
DUCKETTRICH=simulateHouse(9,5,11,15,3,'richer');
DUCKETTYEAR=simulateHouse(9,5,11,15,3,'classyear');
bruteforcemincut(DUCKETTYEAR)
bruteforcemincut(DUCKETTRICH)
bruteforcemincut(DUCKETTDIS)
%%
ALBRIGHTRICH=simulateHouse(14,9,20,25,3,'richer');
ALBRIGHTYEAR=simulateHouse(14,9,20,25,3,'classyear');
ALBRIGHTDIS=simulateHouse(14,9,20,25,3,'distance');
bruteforcemincut(ALBRIGHTYEAR)
bruteforcemincut(ALBRIGHTRICH)
bruteforcemincut(ALBRIGHTDIS)
%%
CHAPINRICH=simulateHouse(14,8,27,21,3,'richer');
CHAPINDIS=simulateHouse(14,8,27,21,3,'distance');
CHAPINYEAR=simulateHouse(14,8,27,21,3,'classyear');
bruteforcemincut(CHAPINYEAR)
bruteforcemincut(CHAPINRICH)
bruteforcemincut(CHAPINDIS)
%%
HUBBARDRICH=simulateHouse(6,6,18,24,3,'richer');
HUBBARDYEAR=simulateHouse(6,6,18,24,3,'classyear');
HUBBARDDIS=simulateHouse(6,6,18,24,3,'distance');
bruteforcemincut(HUBBARDYEAR)
bruteforcemincut(HUBBARDRICH)
bruteforcemincut(HUBBARDDIS)
%%
MORROWRICH=simulateHouse(9,11,28,41,3,'richer');
MORROWYEAR=simulateHouse(9,11,28,41,3,'classyear');
MORROWDIS=simulateHouse(9,11,28,41,3,'distance');
bruteforcemincut(MORROWYEAR)
bruteforcemincut(MORROWRICH)
bruteforcemincut(MORROWDIS)
%%
PARKAXRICH=simulateHouse(5,2,3,5,3,'richer');
PARKAXYEAR=simulateHouse(5,2,3,5,3,'classyear');
PARKAXDIS=simulateHouse(5,2,3,5,3,'distance');
bruteforcemincut(PARKAXYEAR)
bruteforcemincut(PARKAXRICH)
bruteforcemincut(PARKAXDIS)